name: Backend EC2 Deployment

on:
  push:
    paths:
      - "server/**"
    branches:
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Prepare the environment
        run: npm install

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --exclude=node_modules --delete
          path: ./server/
          remote_path: /home/ec2-user/fp-project/server/
          remote_host: ${{ secrets.EC2_IP }}
          remote_user: ec2-user
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart Node.js app with PM2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_IP }} "cd /home/ec2-user/fp-project/server/ && pm2 restart server.js"
