name: Backend EC2 Deployment

on:
  push:
    paths:
      - "server/**"
    branches:
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_IP: ${{ secrets.EC2_IP }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Debug Workflow Environment
        run: |
          echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
          ls -la ~/.ssh

      - name: Set up SSH key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Debug After SSH Key Setup
        run: ls -la ~/.ssh

      - name: Copy server folder to EC2
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./server ec2-user@$EC2_IP:/home/ec2-user/fp-project/server

      - name: SSH into EC2 and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$EC2_IP '
            cd /home/ec2-user/fp-project/ &&
            npm install &&
            pm2 restart server.js
          '
