name: Backend EC2 Deployment

on:
  push:
    paths:
      - "server/**"
    branches:
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add EC2 host key to known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Set up private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key && chmod 600 ~/.ssh/private_key

      - name: Copy server folder to EC2
        run: rsync -av --exclude "node_modules" ./server/ ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/fp-project/

      - name: SSH into EC2 and run commands
        run: |
          ssh -i ~/.ssh/private_key ec2-user@${{ secrets.EC2_IP }} '
            cd /home/ec2-user/fp-project/ &&
            npm install &&
            pm2 restart server.js
          '
