name: Backend EC2 Deployment

on:
  push:
    paths:
      - "server/**"
    branches:
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_IP }}
          DB_URL: ${{ secrets.DB_URL }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${HOSTNAME} '
            cd /home/ec2-user/fp-project/server &&
            git checkout aws &&
            git pull origin aws &&
            export DB_URL='${DB_URL}' &&
            npm install &&
            pm2 restart server.js
          '
