name: Backend EC2 Deployment

on:
  push:
    paths:
      - "server/**"
    branches:
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add EC2 host key to known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Set up private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key && chmod 600 ~/.ssh/private_key

      - name: SSH into EC2 and set environment variables
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key ec2-user@${{ secrets.EC2_IP }} '
            cd /home/ec2-user/fp-project/server &&
            export DB_URL=${{ secrets.DB_URL }}'
      - name: Debugging Info
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory: $(ls -la)"

      - name: Install Node.js dependencies and pm2
        run: |
          npm install
