name: Backend EC2 Deployment

on:
  push:
    paths:
      - "server/**"
    branches:
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Copy server folder to EC2
        run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./server ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/fp-project/server

      - name: SSH into EC2 and run commands
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_IP }} '
            cd /home/ec2-user/fp-project/ &&
            npm install &&
            pm2 restart server.js
          '
